# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 742e938d2cd94c0fd0932dde24256bfeea40b92fb02d4af44058dee0f1bfeee95368a1cb5105e09518fb57a126c149c8c7da89a38f8146d5f8a2e12e8c664fa3

test:
  secret_key_base: 6e4a816c6fc9da12b37f1775b76a8260f1001a6efef8c5016279164b61db2fbd737263857891a4456f59bf53278cbb06be9f1f0f0f86a9c8d04500437a255a12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
